### ISSUE TITLE
cannot get it running with angular-cli and angular 2+

### ISSUE THREAD

**Issue by homofortis** [justindujardin/ng2-material#317]
Any attempt to refer ng2-material components causes typescript errors as : 

ERROR in [default] /Users/zardoz/Developer/SNBA/dash/node_modules/ng2-material/components/backdrop/backdrop.d.ts:1:0 
Cannot find type definition file for 'core-js'.

ERROR in [default] /Users/zardoz/Developer/SNBA/dash/node_modules/ng2-material/components/data-table/data_table.d.ts:1:0 
Cannot find type definition file for 'core-js'.

ERROR in [default] /Users/zardoz/Developer/SNBA/dash/node_modules/ng2-material/components/dialog/dialog.d.ts:1:0 
Cannot find type definition file for 'core-js'.

ERROR in [default] /Users/zardoz/Developer/SNBA/dash/node_modules/ng2-material/components/pagination/pagination.d.ts:1:0 
Cannot find type definition file for 'core-js'.

ERROR in [default] /Users/zardoz/Developer/SNBA/dash/node_modules/ng2-material/core/util/animate.d.ts:1:0 
Cannot find type definition file for 'core-js'.

Here is my package.json:

{
  "name": "dash",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.1.1",
    "@angular/compiler": "^2.1.1",
    "@angular/core": "^2.1.1",
    "@angular/forms": "^2.1.1",
    "@angular/http": "^2.1.1",
    "@angular/material": "^2.0.0-alpha.9-3",
    "@angular/platform-browser": "^2.1.1",
    "@angular/platform-browser-dynamic": "^2.1.1",
    "@angular/router": "^3.1.1",
    "angular-in-memory-web-api": "github:angular/in-memory-web-api",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ng2-material": "^0.8.1",
    "rxjs": "5.0.0-rc.1",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.6.26"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.35",
    "angular-cli": "1.0.0-beta.18",
    "codelyzer": "~1.0.0-beta.3",
    "es6-promise-loader": "^1.0.2",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.6.0",
    "tslint": "3.15.1",
    "typescript": "2.0.3"
  }
}

Material itself is running fine. Am I doing something wrong? What is the right way to use the ng2-material components (the demo app documentation is outdated)?

**Comment by homofortis** [comment]
Looks like this project is abandoned in favour of angular/material2...

**Comment by balnix** [comment]
What worked for me:


In your module add:
```
import { Ng2MaterialModule } from 'ng2-material';
@NgModule({
  imports: [Ng2MaterialModule.forRoot()]
```

Add in your global styles.scss:
```
@import './../node_modules/ng2-material/all.scss';
```

Remove line:
```
"lib": ["es6", "dom"]
```
from tsconfig.json

And install:
```
"@types/core-js": "^0.9.34",
```

**Comment by arlowhite** [comment]
@balnix thanks! Had the same core-js issue; your config fixed it.

**ng2-material team,**
The import documentation here should be updated:
https://justindujardin.github.io/ng2-material/#/
Also, I think you should list the core-js workaround in the installing documentation.

One last thing. I have feature modules being loaded by the router.
**app-routing.module.ts**
`loadChildren: 'app/my-feature.module#MyFeatureModule'`
`preloadingStrategy: PreloadAllModules`

When I put **Ng2MaterialModule.forRoot()** in _app.module.ts_ imports, the ng2-material component is not found. 

> EXCEPTION: Uncaught (in promise): Error: Template parse errors:
> 'md-data-table' is not a known element

So I also put **Ng2MaterialModule.forRoot()** in **my-feature.module** imports, which fixes the issue.

Is it ok to import twice like this? Should I re-export from the feature module (similar to RouterModule)?
Do this?: `exports: [RouterModule, Ng2MaterialModule]`

**Comment by aguarino77** [comment]
@balnix, by using your strategy I get

ERROR in ./~/css-loader?sourcemap!./~/ng2-material/all.scss
Module not found: Error: Can't resolve './core' in '/Users/andrea/Documents/GIT/kitchen02/node_modules/ng2-material'
 @ ./~/css-loader?sourcemap!./~/ng2-material/all.scss 3:10-64
 @ ./~/css-loader?sourcemap!./~/postcss-loader!./src/styles.css
 @ ./src/styles.css
 @ multi styles

ERROR in ./~/css-loader?sourcemap!./~/ng2-material/all.scss
Module not found: Error: Can't resolve './components' in '/Users/andrea/Documents/GIT/kitchen02/node_modules/ng2-material'
 @ ./~/css-loader?sourcemap!./~/ng2-material/all.scss 4:10-70
 @ ./~/css-loader?sourcemap!./~/postcss-loader!./src/styles.css
 @ ./src/styles.css
 @ multi styles

Any idea why?
I am using Angular 2.2.1 with angular-cli

**Comment by aguarino77** [comment]
Fixed by NOT adding in global styles.scss:
~~@import './../node_modules/ng2-material/all.scss';~~

but setting in angular-cli.json
```
"styles": [
        "styles.css",
        "../node_modules/ng2-material/all.scss",
      ],
```

**Comment by askaFed** [comment]
@balnix 
I've done the same, but it still doesn't work. Could you please share your  tsconfig?

**Comment by elmeerr** [comment]
Hi everyone, I have the same problem but I do not want to install @types/core-js because it already exists in typescript...removing this references to core.js in the `d.ts` files solve the problem but it's not the best approach as each time you install ng2-material you'll need to remove those references. I was thinking that probably this reference is no longer necessary and the ng2-material should rely on typescript ES6 type definition instead of using core-js. I said that because installing @types/core-js cause my application to run errors like this one explained [here](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/) ...but for now, I'll use this workaround.
